easy_admin:
  entities:
    # List the entity class name you want to manage
    - App\Entity\Categorie
    - App\Entity\Produit
    - App\Entity\Utilisateur
    - App\Entity\Panier
    - App\Entity\Commande